### ISSUE TITLE
Gescheiterte JSON-Abfrage in device.py verursacht reihenweise Exceptions

### ISSUE THREAD

**Issue by MiOrt** [snaptec/openWB#2490]
Wenn sich bei Dunkelheit mein Fronius ausschaltet und das Interface nicht mehr erreichbar ist, tauchen folgende Zeilen im Log auf. Anscheinend wird eine gescheiterte JSON-Abfrage in **/packages/modules/json/device.py** nicht korrekt abgefangen.

Darauf folgen dann eine Reihe weiterer Exceptions, die vermutlich durch die fehlgeschlagene Abfrage verursacht werden.

Ich denke, dass das eingeräumte Timeout bei der Abfrage zusätzlich die Dauer der Ausführung der Regelschleife beeinflusst, da mit Beginn der Exceptions auch Fatal-Logs der Regelschleife geschrieben werden.

> OSError: [Errno 113] No route to host
sock.connect(sa)
File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 85, in create_connection
raise err
File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 95, in create_connection
(self._dns_host, self.port), self.timeout, **extra_kw
File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connection.py", line 175, in _new_conn
Traceback (most recent call last):
2022-11-10 17:33:56: PID: 2523: root: Json Wechselrichter: FaultState FaultStateLevel.ERROR, FaultStr Die Verbindung zum Server http://192.168.30.6/solar_api/v1/GetPowerFlowRealtimeData.fcgi ist fehlgeschlagen. Überprüfe Adresse und Netzwerk., Traceback:

**Comment by benderl** [comment]
Doch, die Exception wird abgefangen, der Traceback jedoch geloggt, damit man den Fehler nicht verschleiert. Schließlich gibt es keinen Unterschied zwischen einer falschen IP und einem schlafenden WR.

Da die Abfrage mehrere Sekunden auf die Antwort wartet, kommt es natürlich auch zu längeren Regelschleifen, die je nach Dauer mit "warning" oder "fatal" geloggt werden.
