### ISSUE TITLE
ERROR: Command errored out with exit status 1

### ISSUE THREAD

**Issue by Macrisu** [snaptec/openWB#2789]
OpenWB 1.9.303
Rpi 3.0b
OS: Buster latest updates

There are problems with the deprecated Python2.

`cat /var/log/openWB.log`

```
 2023-09-18 17:30:37: at_reboot: ...changed
2023-09-18 17:30:37: at_reboot: crontab 2...
2023-09-18 17:30:37: at_reboot: packages 1...
2023-09-18 17:30:43: at_reboot: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
2023-09-18 17:30:44: at_reboot: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
2023-09-18 17:30:46: at_reboot: Collecting evdev
2023-09-18 17:30:46: at_reboot: Using cached evdev-1.6.1.tar.gz (26 kB)
2023-09-18 17:30:48: at_reboot: ERROR: Command errored out with exit status 1:
2023-09-18 17:30:48: at_reboot: command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vDYxGI/evdev/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vDYxGI/evdev/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6qm7Pk
2023-09-18 17:30:48: at_reboot: cwd: /tmp/pip-install-vDYxGI/evdev/
2023-09-18 17:30:48: at_reboot: Complete output (6 lines):
2023-09-18 17:30:48: at_reboot: Traceback (most recent call last):
2023-09-18 17:30:48: at_reboot: File "<string>", line 1, in <module>
2023-09-18 17:30:48: at_reboot: File "/tmp/pip-install-vDYxGI/evdev/setup.py", line 103
2023-09-18 17:30:48: at_reboot: cmd = [sys.executable, 'evdev/genecodes.py', *headers]
2023-09-18 17:30:48: at_reboot: ^
2023-09-18 17:30:48: at_reboot: SyntaxError: invalid syntax
2023-09-18 17:30:48: at_reboot: ----------------------------------------
2023-09-18 17:30:48: at_reboot: ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2023-09-18 17:30:59: at_reboot: 2023-09-18 17:30:59: PID: 2176: upgradeChargeLogs: upgrading charge logs with a price of 0.3 per kWh
2023-09-18 17:30:59: at_reboot: 2023-09-18 17:30:59: PID: 2176: upgradeChargeLogs: upgrading charge logs done
2023-09-18 17:30:59: at_reboot: timezone...
2023-09-18 17:30:59: at_reboot: mosquitto...
2023-09-18 17:30:59: at_reboot: updating mosquitto config file
2023-09-18 17:30:59: at_reboot: Reloading network daemon configuration:: mosquitto.
2023-09-18 17:30:59: at_reboot: python3 packages...
2023-09-18 17:31:00: at_reboot: all required modules are installed
2023-09-18 17:31:00: at_reboot: lxml installed...
2023-09-18 17:31:00: at_reboot: soc_vwid: python3 secrets installed...
2023-09-18 17:31:00: at_reboot: soc_smarteq: python3 secrets installed...
2023-09-18 17:31:08: at_reboot: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
2023-09-18 17:31:10: at_reboot: Requirement already up-to-date: urllib3 in ./.local/lib/python3.7/site-packages (2.0.4)
2023-09-18 17:31:11: PID: 2236: Ramdisk not set up. Maybe we are still booting. (LV0) at 50 main /var/www/html/openWB/regel.sh
2023-09-18 17:31:13: at_reboot: version...
2023-09-18 17:31:13: at_reboot: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2023-09-18 17:31:13: at_reboot: Dload  Upload   Total   Spent    Left  Speed
100    45    0     0  100    45      0    271 --:--:-- --:--:-- --:--:--   271
2023-09-18 17:31:13: at_reboot: clear warning...
2023-09-18 17:31:13: PID: 2254: Stopping OpenWB services (LV0)
2023-09-18 17:31:13: PID: 2254: OpenWB services stopped (LV0)
2023-09-18 17:31:13: PID: 2254: Starting OpenWB services (LV0)
2023-09-18 17:31:13: PID: 2254: modbus tcp server not running! restarting process (LV0)
2023-09-18 17:31:13: PID: 2254: mqtt handler not running! restarting process (LV0)
2023-09-18 17:31:13: PID: 2254: legacy run server is not running. Restarting process (LV0)
2023-09-18 17:31:14: at_reboot: Starting legacy run server
2023-09-18 17:31:14: PID: 2254: Start/restart isss handler in mode daemon. (LV0)
2023-09-18 17:31:14: PID: 2291: legacy run server: Changing log level DEBUG -> WARNING
2023-09-18 17:31:15: at_reboot: update broker...
2023-09-18 17:31:16: at_reboot: etprovider...
2023-09-18 17:31:16: at_reboot: not activated, skipping
2023-09-18 17:31:16: at_reboot: fix upload limit...OS Buster
2023-09-18 17:31:17: at_reboot: 2023-09-18 17:31:17: boot done :-)
/var/www/html/openWB/regel.sh: line 119: ramdisk/heartbeat: No such file or directory
2541
2023-09-18 17:32:01: PID: 2553: Previous regulation loop still running. Skipping. (LV0) at 35 main /var/www/html/openWB/regel.sh

```

**Comment by Macrisu** [comment]
the fix is

`sudo pip install requests Adafruit_MCP4725 pyserial "sysv_ipc == 1.0.1" "evdev == 1.6.0" urllib3`
